### PR TITLE
fix secure scraping instructions

### PR DESCRIPTION
**Pull request by Benjamintf1**

### CODE REVIEW

**Comment by Benjamintf1** [comment]
Designated a reviewer?

**Comment by Benjamintf1** [comment]
do you want me to assign you?
\

**Comment by Benjamintf1** [comment]
oh wait, I don't think I can do that.

**Comment by anita-flegg** [comment]
I think it's OK. It's weird because this Blocked message didn't appear on the change in any other branches, so I thought you added the restriction. I can override the requirement and get around the block.

**Review by anita-flegg — APPROVED** [review]
LGTM

**Pull request merged**
